// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertTfIdfBulk implements pgx.CopyFromSource.
type iteratorForInsertTfIdfBulk struct {
	rows                 []InsertTfIdfBulkParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertTfIdfBulk) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertTfIdfBulk) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UrlID,
		r.rows[0].TokenID,
		r.rows[0].TfIdf,
	}, nil
}

func (r iteratorForInsertTfIdfBulk) Err() error {
	return nil
}

func (q *Queries) InsertTfIdfBulk(ctx context.Context, arg []InsertTfIdfBulkParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tf_idf_index"}, []string{"url_id", "token_id", "tf_idf"}, &iteratorForInsertTfIdfBulk{rows: arg})
}
