// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const addVector = `-- name: AddVector :one
insert into vector_index (
	url_id, embedding
) values (
	$1, $2
)
returning url_id, embedding
`

type AddVectorParams struct {
	UrlID     int64
	Embedding pgvector.Vector
}

func (q *Queries) AddVector(ctx context.Context, arg AddVectorParams) (VectorIndex, error) {
	row := q.db.QueryRow(ctx, addVector, arg.UrlID, arg.Embedding)
	var i VectorIndex
	err := row.Scan(&i.UrlID, &i.Embedding)
	return i, err
}

const deleteRawContent = `-- name: DeleteRawContent :exec
delete from raw_content where url_id = $1
`

func (q *Queries) DeleteRawContent(ctx context.Context, urlID int64) error {
	_, err := q.db.Exec(ctx, deleteRawContent, urlID)
	return err
}

const getCountsForToken = `-- name: GetCountsForToken :many
select url_id, "count"
from tf_idf_counts
where token_id = $1
`

type GetCountsForTokenRow struct {
	UrlID int64
	Count int32
}

func (q *Queries) GetCountsForToken(ctx context.Context, tokenID int64) ([]GetCountsForTokenRow, error) {
	rows, err := q.db.Query(ctx, getCountsForToken, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountsForTokenRow
	for rows.Next() {
		var i GetCountsForTokenRow
		if err := rows.Scan(&i.UrlID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentCount = `-- name: GetDocumentCount :one
select count(distinct url_id) as total
from tf_idf_counts
`

func (q *Queries) GetDocumentCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getDocumentFrequencyByToken = `-- name: GetDocumentFrequencyByToken :one
select count(distinct url_id) as df
from tf_idf_counts
where token_id = $1
`

func (q *Queries) GetDocumentFrequencyByToken(ctx context.Context, tokenID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentFrequencyByToken, tokenID)
	var df int64
	err := row.Scan(&df)
	return df, err
}

const getTokenIDs = `-- name: GetTokenIDs :many
select id
from tf_idf_tokens
`

func (q *Queries) GetTokenIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getTokenIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnprocessedRawContent = `-- name: GetUnprocessedRawContent :many
select r.url_id, r.content
from raw_content r
where not exists (select 1 from processed_content p where p.url_id = r.url_id)
`

type GetUnprocessedRawContentRow struct {
	UrlID   int64
	Content string
}

func (q *Queries) GetUnprocessedRawContent(ctx context.Context) ([]GetUnprocessedRawContentRow, error) {
	rows, err := q.db.Query(ctx, getUnprocessedRawContent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnprocessedRawContentRow
	for rows.Next() {
		var i GetUnprocessedRawContentRow
		if err := rows.Scan(&i.UrlID, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTfIdfBatch = `-- name: InsertTfIdfBatch :exec
insert into tf_idf_index (
	url_id, token_id, tf_idf
) values (
	$1, $2, $3
)
`

type InsertTfIdfBatchParams struct {
	UrlID   int64
	TokenID int64
	TfIdf   float64
}

func (q *Queries) InsertTfIdfBatch(ctx context.Context, arg InsertTfIdfBatchParams) error {
	_, err := q.db.Exec(ctx, insertTfIdfBatch, arg.UrlID, arg.TokenID, arg.TfIdf)
	return err
}

type InsertTfIdfBulkParams struct {
	UrlID   int64
	TokenID int64
	TfIdf   float64
}

const moveToProcessed = `-- name: MoveToProcessed :exec
insert into processed_content (url_id, content)
select r.url_id, r.content from raw_content r where r.url_id = $1
`

func (q *Queries) MoveToProcessed(ctx context.Context, urlID int64) error {
	_, err := q.db.Exec(ctx, moveToProcessed, urlID)
	return err
}
