// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getCountsForToken = `-- name: GetCountsForToken :many
select url_id, "count"
from tf_idf_counts
where token_id = $1
`

type GetCountsForTokenRow struct {
	UrlID int64
	Count int32
}

func (q *Queries) GetCountsForToken(ctx context.Context, tokenID int64) ([]GetCountsForTokenRow, error) {
	rows, err := q.db.Query(ctx, getCountsForToken, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCountsForTokenRow
	for rows.Next() {
		var i GetCountsForTokenRow
		if err := rows.Scan(&i.UrlID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentCount = `-- name: GetDocumentCount :one
select count(distinct url_id) as total
from tf_idf_counts
`

func (q *Queries) GetDocumentCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getDocumentFrequencyByToken = `-- name: GetDocumentFrequencyByToken :one
select count(distinct url_id) as df
from tf_idf_counts
where token_id = $1
`

func (q *Queries) GetDocumentFrequencyByToken(ctx context.Context, tokenID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentFrequencyByToken, tokenID)
	var df int64
	err := row.Scan(&df)
	return df, err
}

const getTokenIDs = `-- name: GetTokenIDs :many
select id
from tf_idf_tokens
`

func (q *Queries) GetTokenIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getTokenIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTfIdfBatch = `-- name: InsertTfIdfBatch :exec
insert into tf_idf_index (
	url_id, token_id, tf_idf
) values (
	$1, $2, $3
)
`

type InsertTfIdfBatchParams struct {
	UrlID   int64
	TokenID int64
	TfIdf   float64
}

func (q *Queries) InsertTfIdfBatch(ctx context.Context, arg InsertTfIdfBatchParams) error {
	_, err := q.db.Exec(ctx, insertTfIdfBatch, arg.UrlID, arg.TokenID, arg.TfIdf)
	return err
}
