// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const getTokenIds = `-- name: GetTokenIds :one
SELECT 
	id,
	token
FROM tf_idf_tokens
WHERE token = $1
`

func (q *Queries) GetTokenIds(ctx context.Context, token string) (TfIdfToken, error) {
	row := q.db.QueryRow(ctx, getTokenIds, token)
	var i TfIdfToken
	err := row.Scan(&i.ID, &i.Token)
	return i, err
}

const tFIDFSearch = `-- name: TFIDFSearch :many
SELECT
	u.id,
	u.url,
	SUM(ti.tf_idf) AS relevance_score,
	COUNT(DISTINCT ti.token_id) AS matched_tokens
FROM tf_idf_index ti
JOIN urls u ON u.id = ti.url_id
JOIN tf_idf_tokens t ON t.id = ti.token_id
WHERE t.token = ANY($1::text[])
GROUP BY u.id, u.url
ORDER BY relevance_score DESC, matched_tokens DESC
LIMIT $2::int
`

type TFIDFSearchParams struct {
	Tokens []string
	Limit  int32
}

type TFIDFSearchRow struct {
	ID             int64
	Url            string
	RelevanceScore int64
	MatchedTokens  int64
}

// TF-IDF search with token matching
func (q *Queries) TFIDFSearch(ctx context.Context, arg TFIDFSearchParams) ([]TFIDFSearchRow, error) {
	rows, err := q.db.Query(ctx, tFIDFSearch, arg.Tokens, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TFIDFSearchRow
	for rows.Next() {
		var i TFIDFSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.RelevanceScore,
			&i.MatchedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vectorSearch = `-- name: VectorSearch :many
SELECT
	u.id,
	u.url
	-- (1 - (vi.embedding <-> sqlc.arg('query_embedding')::vector)) AS similarity_score
FROM vector_index vi
JOIN urls u ON u.id = vi.url_id
WHERE vi.embedding IS NOT NULL
ORDER BY vi.embedding <#> $1::vector
LIMIT $2::int
`

type VectorSearchParams struct {
	QueryEmbedding pgvector.Vector
	Limit          int32
}

// Vector similarity search
func (q *Queries) VectorSearch(ctx context.Context, arg VectorSearchParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, vectorSearch, arg.QueryEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(&i.ID, &i.Url); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveEvaluation = `-- name: SaveEvaluation :exec
INSERT INTO evaluation_results (query, search_type, score)
VALUES ($1, $2, $3)
`

type SaveEvaluationParams struct {
	Query      string
	SearchType string
	Score      int32
}

func (q *Queries) SaveEvaluation(ctx context.Context, arg SaveEvaluationParams) error {
	_, err := q.db.Exec(ctx, saveEvaluation, arg.Query, arg.SearchType, arg.Score)
	return err
}
