// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const getEvaluationSummary = `-- name: GetEvaluationSummary :many
SELECT search_type, 
       category,
       COUNT(*) AS total, 
       SUM(CASE WHEN is_relevant THEN 1 ELSE 0 END) AS relevant
FROM evaluation_results
GROUP BY search_type, category
`

type GetEvaluationSummaryRow struct {
	SearchType string
	Category   string
	Total      int64
	Relevant   int64
}

func (q *Queries) GetEvaluationSummary(ctx context.Context) ([]GetEvaluationSummaryRow, error) {
	rows, err := q.db.Query(ctx, getEvaluationSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEvaluationSummaryRow
	for rows.Next() {
		var i GetEvaluationSummaryRow
		if err := rows.Scan(
			&i.SearchType,
			&i.Category,
			&i.Total,
			&i.Relevant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenIds = `-- name: GetTokenIds :one
SELECT 
	id,
	token
FROM tf_idf_tokens
WHERE token = $1
`

func (q *Queries) GetTokenIds(ctx context.Context, token string) (TfIdfToken, error) {
	row := q.db.QueryRow(ctx, getTokenIds, token)
	var i TfIdfToken
	err := row.Scan(&i.ID, &i.Token)
	return i, err
}

const saveEvaluation = `-- name: SaveEvaluation :exec
INSERT INTO evaluation_results (query, category, url, search_type, is_relevant)
VALUES ($1, $2, $3, $4, $5)
`

type SaveEvaluationParams struct {
	Query      string
	Category   string
	Url        string
	SearchType string
	IsRelevant bool
}

func (q *Queries) SaveEvaluation(ctx context.Context, arg SaveEvaluationParams) error {
	_, err := q.db.Exec(ctx, saveEvaluation,
		arg.Query,
		arg.Category,
		arg.Url,
		arg.SearchType,
		arg.IsRelevant,
	)
	return err
}

const tFIDFSearch = `-- name: TFIDFSearch :many
SELECT
	u.id,
	u.url,
	u.title,
	agg.relevance_score,
	agg.matched_tokens
FROM (
    SELECT url_id, SUM(tf_idf)::double precision AS relevance_score, COUNT(DISTINCT token_id) AS matched_tokens
    FROM tf_idf_index
    WHERE token_id IN (SELECT id FROM tf_idf_tokens WHERE token = ANY($1::text[]))
    GROUP BY url_id
    ORDER BY relevance_score DESC, matched_tokens DESC
    LIMIT $2::int
) AS agg
JOIN urls u ON u.id = agg.url_id
`

type TFIDFSearchParams struct {
	Tokens []string
	Limit  int32
}

type TFIDFSearchRow struct {
	ID             int64
	Url            string
	Title          string
	RelevanceScore float64
	MatchedTokens  int64
}

// TF-IDF search with token matching
func (q *Queries) TFIDFSearch(ctx context.Context, arg TFIDFSearchParams) ([]TFIDFSearchRow, error) {
	rows, err := q.db.Query(ctx, tFIDFSearch, arg.Tokens, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TFIDFSearchRow
	for rows.Next() {
		var i TFIDFSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.RelevanceScore,
			&i.MatchedTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vectorSearch = `-- name: VectorSearch :many
SELECT
	u.id,
	u.url,
	u.title
FROM vector_index vi
JOIN urls u ON u.id = vi.url_id
WHERE vi.embedding IS NOT NULL
ORDER BY vi.embedding <#> $1::vector
LIMIT $2::int
`

type VectorSearchParams struct {
	QueryEmbedding pgvector.Vector
	Limit          int32
}

// Vector similarity search
func (q *Queries) VectorSearch(ctx context.Context, arg VectorSearchParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, vectorSearch, arg.QueryEmbedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(&i.ID, &i.Url, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
