// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ProcessedContent struct {
	UrlID       int64
	Content     string
	ProcessedAt pgtype.Timestamptz
}

type RawContent struct {
	UrlID     int64
	Content   string
	CreatedAt pgtype.Timestamptz
}

type TfIdfCount struct {
	UrlID   int64
	TokenID int64
	Count   int32
}

type TfIdfIndex struct {
	UrlID   int64
	TokenID int64
	TfIdf   float64
}

type TfIdfToken struct {
	ID    int64
	Token string
}

type Url struct {
	ID    int64
	Url   string
	Title string
}

type VectorIndex struct {
	UrlID     int64
	Embedding pgvector.Vector
}
