// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/pgvector/pgvector-go"
)

const addCount = `-- name: AddCount :one
insert into tf_idf_counts (
	url_id, token_id, "count"
) values (
	$1, $2, $3
) on conflict (
	url_id, token_id
) do update set "count" = excluded."count"
returning url_id, token_id, count
`

type AddCountParams struct {
	UrlID   int64
	TokenID int64
	Count   int32
}

func (q *Queries) AddCount(ctx context.Context, arg AddCountParams) (TfIdfCount, error) {
	row := q.db.QueryRow(ctx, addCount, arg.UrlID, arg.TokenID, arg.Count)
	var i TfIdfCount
	err := row.Scan(&i.UrlID, &i.TokenID, &i.Count)
	return i, err
}

const addRawContent = `-- name: AddRawContent :exec
insert into raw_content (
	url_id, content
) values (
	$1, $2
)
`

type AddRawContentParams struct {
	UrlID   int64
	Content string
}

func (q *Queries) AddRawContent(ctx context.Context, arg AddRawContentParams) error {
	_, err := q.db.Exec(ctx, addRawContent, arg.UrlID, arg.Content)
	return err
}

const addToken = `-- name: AddToken :one
insert into tf_idf_tokens (
	token
) values (
	$1
) on conflict (
	token
) do update set token = tf_idf_tokens.token
returning id
`

func (q *Queries) AddToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, addToken, token)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addURL = `-- name: AddURL :one
insert into urls (
	url, title
) values (
	$1, $2
) on conflict (
	url
) do update set url = urls.url
returning id
`

type AddURLParams struct {
	Url   string
	Title string
}

func (q *Queries) AddURL(ctx context.Context, arg AddURLParams) (int64, error) {
	row := q.db.QueryRow(ctx, addURL, arg.Url, arg.Title)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addVector = `-- name: AddVector :one
insert into vector_index (
	url_id, embedding
) values (
	$1, $2
)
returning url_id, embedding
`

type AddVectorParams struct {
	UrlID     int64
	Embedding pgvector.Vector
}

func (q *Queries) AddVector(ctx context.Context, arg AddVectorParams) (VectorIndex, error) {
	row := q.db.QueryRow(ctx, addVector, arg.UrlID, arg.Embedding)
	var i VectorIndex
	err := row.Scan(&i.UrlID, &i.Embedding)
	return i, err
}
